### ISSUE TITLE
@uauth/web3-react Critical dependency: the request of a dependency is an expression warning in WebPack

### ISSUE THREAD

**Issue by ug02fast** [unstoppabledomains/uauth#3]
There's currently a bug in this package that causes this error to appear: 
```
./node_modules/@uauth/js/node_modules/@unstoppabledomains/resolution/build/utils/requireOrFail.js
Critical dependency: the request of a dependency is an expression
```

![image](https://user-images.githubusercontent.com/5507707/149179929-f308b501-fbe5-40c7-b399-ca1d175f2912.png)

Seems like there is some solution pointed out in this thread: https://github.com/unstoppabledomains/resolution/issues/150

Is it possible to fix this warning for this package?

**Comment by rohithandique** [comment]
hi @ug02fast , were you able to find a solution for this? I'm using the same library with create-react-app and nothing gets rendered on the screen because of this. :(

![image](https://user-images.githubusercontent.com/48451078/150641287-291b189f-fc52-4385-acc3-8587f47f1287.png)

**Comment by ug02fast** [comment]
Nope, our FE is built with CRA too and workarounds such as ignoring the warning/error are swallowed by CRA so we're at the mercy of UD team to update this before we integrate.

**Comment by ug02fast** [comment]
resolved in latest version of @uauth/web3-react
